INSERT INTO GAME_INFORMATION (GAME_ID, GAME_TITLE, GAME_VERSION, GAME_EXECUTION_PATH, GAME_LOG_PATH) VALUES (2, "Pikachu Ball", "1.0.0", "I:/AutomatedQA/MYSQL/GameInfoTest/Pikachu.EXE", "I:\AutomatedQA\MYSQL\LogTest");
INSERT INTO GAME_INFORMATION (GAME_ID, GAME_TITLE, GAME_VERSION, GAME_EXECUTION_PATH, GAME_LOG_PATH) VALUES (3, "Pikachu Ball", "2.0.0", "I:/AutomatedQA/MYSQL/GameInfoTest/Pikachu_2.0.0.EXE", "I:\AutomatedQA\MYSQL\LogTest");

SELECT * from game_information;
SELECT GAME_EXECUTION_PATH FROM GAME_INFORMATION WHERE GAME_TITLE = "Pikachu Ball" and GAME_VERSION = "1.0.0";
SELECT GAME_EXECUTION_PATH FROM GAME_INFORMATION WHERE GAME_TITLE = "Pikachu Ball" and GAME_VERSION = "2.0.0";
